### ISSUE TITLE
Support for transforming objects

### ISSUE THREAD

**Issue by blaumeise20** [QuantumBadger/Speedy2D#46] opened 2021-12-25 09:22 UTC
Web canvas has features like .translate and .rotate. I couldn't find a way to do this with speedy2d. Please add this!

**Comment by QuantumBadger** [comment] 2021-12-28 13:15
Thanks for the request, however this is a duplicate of https://github.com/QuantumBadger/Speedy2D/issues/18. From a performance perspective I think it makes more sense to do any matrix transformations in the application code.

**Closed by QuantumBadger** 2021-12-28 13:15 UTC
